print("Zu Ihrer Information: ")
print("Plus = +")
print("Minus = -")
print("Mal = *")
print("Geteilt = /")
print("Hoch = **")
zahl1=float(input("Geben Sie Ihre erste Zahl ein: "))
zeichen=input("Geben Sie Ihre Rechenmethode ein: ")
zahl2=float(input("Geben Sie Ihre zweite Zahl ein: "))
print("Ihr Ergebnis ist: ", zahl1, zeichen, zahl2)
